### ISSUE TITLE
Enemy circling around the king 

### ISSUE THREAD

**Issue by buildersteven4** [Science-Club-PNC/CookieClickerTD#10]
Currently the enemies just go to the centre of the king cookie. That behaviour is unwanted. The enemies should gather at the edge of the king cookie while trying to maintain some distance from other enemies. So with a large amount of cursors around the king they would form a evenly spread circle of enemies. Maybe in manner similar as shown below.
![image](https://cloud.githubusercontent.com/assets/7680806/3497787/b5e2629e-05ee-11e4-9a25-04424873aeec.png)

**Comment by buildersteven4** [comment]
done

**Comment by mid-kid** [comment]
...which commit?
