### ISSUE TITLE
Wave systeem

### ISSUE THREAD

**Issue by mid-kid** [Science-Club-PNC/CookieClickerTD#3]
Spreekt volgens mij voor zich.
Net zoals in andere TD's, komen er elke zoveel tijd wat enemies, natuurlijk elke keer wat sterker.
Hiervoor hebben we enemy classes/levels nodig: #2

**Comment by buildersteven4** [comment]
Ik sluit deze issue, omdat het alleen nog maar getweaked moet worden.
