### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mid-kid** [Science-Club-PNC/CookieClickerTD#5]
Als er geen license op de source code staat, dan staat het volgens mij automatisch onder de "All rights reserved" license, maar toch is het altijd fijn om duidelijk neer te zetten wat mensen mogen doen met onze source code. Hiervoor hebben we een license nodig.
Meestal neem ik GPLv3 of WTFPL.
GPLv3 zegt dat mensen zelf iets van je code mogen maken, zolang het geen clone is met een andere naam, en de source code word gereleased. Maar volgens mij mag GPL code geen closed source libraries gebruiken. (_coughgamemakercough_)
WTFPL zegt dat het je niet boeit wat mensen er mee doen.
Voor de rest heb ik amper naar licenties gekeken, maar geef je voorstel.
Ik stem voor WTFPL, aangezien dit meer "voor de lol" is dan iets anders.
Reference site voor licenses: https://tldrlegal.com/

**Comment by buildersteven4** [comment]
is het mogelijk om later nog te switchen? heel mischien weten we het op de andriod & iOs markt te krijgen.

**Comment by mid-kid** [comment]
Ja, het is mogelijk voor de copyright holder(s) om de licentie later te switchen, en de android/ios market boeit het niet welke licentie je gebruikt.

**Comment by buildersteven4** [comment]
alleen zou iemand nog een spel kopen die open source is?

**Comment by mid-kid** [comment]
Nee, maar moeten we het verkopen?
Wat mij betreft is dat alles behalve nodig.
Zoals we het nu doen is het al wat je open source zou noemen.
Als je echt zo nodig geld moet verdienen, kan je altijd om donaties vragen, of misschien een betaalde versie met wat "extras".

**Comment by mid-kid** [comment]
Of je kan the owncloud way gaan, en om geld vragen op google play ook als het open source is.
Mensen betalen om het "gemak" van distributie op GPlay.

**Comment by buildersteven4** [comment]
ik zeg niet dat we het moeten verkopen. maar de optie open houden lijkt me wel nice. just in case :)

donaties kan wel... extras zou waarschijnlijk uitlopen op zo'n micro-transaction gebeuren. dus het hele GPlay gebeuren klinkt het nicest. alleen wat is owncloud?

**Comment by mid-kid** [comment]
[Owncloud](http://owncloud.org/) is een self-hosted dropbox clone. Ze hebben een app voor android [op GPlay](https://play.google.com/store/search?q=owncloud) die betaald is, maar toch open source/gratis staat [op github](https://github.com/owncloud/android) en [op f-droid](https://f-droid.org/repository/browse/?fdfilter=owncloud&fdid=com.owncloud.android). Heb het een tijdje op mijn Raspberry Pi gehad, maar heb er niks aan als mijn ouders constant de stekker er uit trekken.

**Comment by mid-kid** [comment]
Voorlopig hebben we besloten om het onder de LGPL te stoppen onder mijn naam.
Misschien veranderd hier later nog wat aan.
