### ISSUE TITLE
Cookie stays clicked

### ISSUE THREAD

**Issue by mid-kid** [Science-Club-PNC/CookieClickerTD#6]
Als je op het koekje klikt, dan word ie in gedrukt, als je je muis ingedrukt houd, ergens anders staan en je laat los, dan blijft het koekje ingedrukt. (Daarnaast kan je met de muis release een nieuwe toren maken)

**Comment by buildersteven4** [comment]
de hele on click event is toch al onbetrouwbaar. het gebruikt mouse_x en mouse_y... dus je kan het king cookie aan klikken in het stats menu. samen met wat andere problemen.

**Comment by mid-kid** [comment]
Dat (mouse_{x,y} probleem) was al gefixt toen ik deze issue heb geopend...

**Comment by buildersteven4** [comment]
nope.de standaart mouse button pressed event thingy gebruikt mouse_{x,y}. dus iemand moet de global on click thing gebruiken en zelf de filter muis locatie filter schrijven.

**Comment by mid-kid** [comment]
Palm, meet face.
Said, ik had dat alarm weg gehaald omdat dat gay is.
Het is de bedoeling dat je geld krijgt als je je muis los laat (net zoals in de originele game).
Ik wou dat hebben, zonder dat het koekje ingedrukt kon blijven, daarom deze bug.

**Comment by mid-kid** [comment]
There you go, closing.
