### ISSUE TITLE
Don't lose money when clicking cookie.

### ISSUE THREAD

**Issue by mid-kid** [Science-Club-PNC/CookieClickerTD#7]
Het was jouw geweldige idee om dat toe te passen nog voordat we een build menu hebben, dus jij mag het fixen.

[drie](https://github.com/mid-kid/CookieClickerTD/commit/8c19215dbac03d90b1487f0845bee0782b005c73) [fkn](https://github.com/mid-kid/CookieClickerTD/commit/e69a4707134333928e7f1501cec5ac372ae5da0b) [commits](https://github.com/mid-kid/CookieClickerTD/commit/14dcb9bd0d28e422becbbf35b4cc45f74a6de01c) om deze bug toe te passen, wereld record. :clap:

**Comment by ghost** [comment]
Fixed

**Comment by mid-kid** [comment]
See #8 for the reason why this is open again.

**Comment by buildersteven4** [comment]
really guys? this really was to easy -__-

_fixed_

**Comment by mid-kid** [comment]
I didn't, because I wanted to see said fix this bug :/

**Comment by buildersteven4** [comment]
yep. me too. but the bug was just too fucking annoying...
