### ISSUE TITLE
Can't place towers.

### ISSUE THREAD

**Issue by mid-kid** [Science-Club-PNC/CookieClickerTD#8]
```
(16:02:36) Steven Vroom: said. test jij ooit wat je maakt?
(16:02:58) Steven Vroom: je laatste commit zorgt er gewoon voor dat je nergens een toren kan plaatsen...
```

[wrongdoing commit](https://github.com/mid-kid/CookieClickerTD/commit/7d255f73c9b57ca9039f9837bb9608ad5cf73b3d)
This says everything

**Comment by buildersteven4** [comment]
already disabled commit that caused this. issue #7 is open again.

**Comment by mid-kid** [comment]
Sorry for the new issue.
